// Include lazy-entry dependencies before the first editor/search interaction.
// These settings do not eagerly load features in the production renderer.
export const devOptimizeDepsInclude = [
  'react',
  'react-dom',
  'react-dom/client',
  'react/jsx-runtime',
  'react-router-dom',
  '@tanstack/react-query',
  'zustand',
  'sonner',
  'lucide-react',
  '@codemirror/language-data',
  '@codemirror/language',
  'platejs',
  'platejs/react',
  '@platejs/basic-nodes',
  '@platejs/basic-nodes/react',
  '@platejs/code-block',
  '@platejs/code-block/react',
  '@platejs/link',
  '@platejs/link/react',
  '@platejs/list-classic',
  '@platejs/list-classic/react',
  '@platejs/markdown',
  '@platejs/media',
  '@platejs/media/react',
  '@platejs/table',
  '@platejs/table/react',
  '@uiw/codemirror-theme-eclipse',
  'lodash-es/escape',
  'lodash-es/throttle',
  'mermaid',
  'fuse.js',
]

export const devWarmupClientFiles = [
  './src/main.tsx',
  './src/App.tsx',
  './src/app/AppLayout.tsx',
  './src/app/AppShellPanels.tsx',
  './src/components/MarkdownEditor.tsx',
  './src/components/TitlebarCommandDialog.tsx',
]
