[package]
name = "marklab-knowledge-engine-core"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
marklab-knowledge-protocol = { path = "../protocol" }
pulldown-cmark.workspace = true
redb = "4.1.0"
ropey.workspace = true
serde.workspace = true
serde_json.workspace = true
tantivy = { version = "0.26.1", default-features = false, features = ["mmap", "lz4-compression"] }
tree-sitter = { workspace = true, optional = true }
tree-sitter-md = { workspace = true, optional = true }
unicode-normalization.workspace = true
unicode-segmentation.workspace = true

[features]
tree-sitter-markdown = ["dep:tree-sitter", "dep:tree-sitter-md"]

[lib]
path = "src/lib.rs"
