export const markdownTemplates: Record<string, string> = {
  mermaid: '```mermaid\ngraph TD\n  A --> B\n```\n',
  'code-typescript': '```typescript\n\n```\n',
  'code-javascript': '```javascript\n\n```\n',
  'code-json': '```json\n{\n  \n}\n```\n',
  'code-bash': '```bash\n\n```\n',
  'code-html': '```html\n\n```\n',
  'callout-note': '> [!NOTE]\n> \n',
  'callout-tip': '> [!TIP]\n> \n',
  'callout-important': '> [!IMPORTANT]\n> \n',
  'callout-warning': '> [!WARNING]\n> \n',
  'callout-caution': '> [!CAUTION]\n> \n',
  footnote: 'Text[^1]\n\n[^1]: Footnote\n',
  frontmatter: '---\ntitle: Untitled\ntags: []\n---\n\n',
  details: '<details>\n<summary>Title</summary>\n\nContent\n\n</details>\n',
  toc: '## Contents\n\n- [Section](#section)\n',
  bold: '**Bold**\n',
  italic: '*Italic*\n',
  'inline-code': '`code`\n',
  strike: '~~Strikethrough~~\n',
}
