export const nativeIpcChannels = {
  appReadyIsReady: 'marklab:app-ready:is-ready',
  appReadySignal: 'marklab:app-ready',
  appReadyWhenReady: 'marklab:app-ready:when-ready',
  clipboardReadImage: 'marklab:clipboard:read-image',
  clipboardReadText: 'marklab:clipboard:read-text',
  clipboardWriteText: 'marklab:clipboard:write-text',
  commandInvoke: 'marklab:command:invoke',
  dialogOpen: 'marklab:dialog:open',
  dialogSave: 'marklab:dialog:save',
  lifecycleGetLaunchInfo: 'marklab:lifecycle:get-launch-info',
  menuCommand: 'marklab:menu:command',
  menuRendererReady: 'marklab:menu:renderer-ready',
  platformGet: 'marklab:platform:get',
  settingsPersistGet: 'marklab:settings:persist:get',
  settingsPersistRemove: 'marklab:settings:persist:remove',
  settingsPersistSet: 'marklab:settings:persist:set',
  shellOpenPath: 'marklab:shell:open-path',
  shellRevealPath: 'marklab:shell:reveal-path',
  windowClose: 'marklab:window:close',
  windowIsMaximized: 'marklab:window:is-maximized',
  windowMaximize: 'marklab:window:maximize',
  windowMinimize: 'marklab:window:minimize',
  windowStartDrag: 'marklab:window:start-drag',
  windowUnmaximize: 'marklab:window:unmaximize',
} as const

export type NativeIpcChannel = (typeof nativeIpcChannels)[keyof typeof nativeIpcChannels]
