const allowedCommandNames = [
  'app-ready',
  'app_get_platform',
  'menu_dispatch',
  'open_current_workspace_in_new_window',
  'open_path_in_new_window',
  'fs_get_root_info',
  'fs_get_snapshot',
  'fs_list_entries',
  'fs_set_root',
  'fs_set_single_file',
  'fs_open_file',
  'fs_read_file',
  'fs_get_workspace_index',
  'fs_get_workspace_graph',
  'fs_get_outline_graph',
  'fs_analyze_markdown_buffer',
  'fs_search_workspace',
  'fs_rebuild_search_index',
  'fs_update_buffer',
  'fs_write_file',
  'fs_flush_buffers',
  'fs_get_buffer_status',
  'fs_get_background_tasks',
  'fs_create_file',
  'fs_create_dir',
  'fs_rename_path',
  'fs_move_path',
  'fs_delete_path',
  'fs_get_path_metadata',
  'fs_open_path_in_system',
  'fs_import_markdown_asset',
  'fs_import_markdown_asset_base64',
  'fs_resolve_markdown_asset',
  'fs_fetch_link_preview',
  'markdown_language_get_completions',
  'markdown_language_get_diagnostics',
  'markdown_language_get_document_symbols',
  'markdown_language_get_definition',
  'markdown_language_get_references',
  'markdown_language_rename_references',
  'markdown_language_get_code_actions',
  'markdown_language_get_hover',
  'list_markdown_files',
  'read_markdown_file',
  'write_markdown_file',
  'git_discover_repo',
  'git_init_repo',
  'git_get_status',
  'git_get_file_diff',
  'git_commit_all',
  'terminal_create',
  'terminal_write',
  'terminal_resize',
  'terminal_close',
  'export_markdown',
  'export_open_output_path',
] as const

const allowedEventNames = [
  'fs-changed',
  'fs-buffer-status',
  'export-task',
  'terminal-output',
  'terminal-exit',
  'menu-action',
  'single-instance',
  'deep-link',
  'app-ready',
  'workspace-session-seed',
  'system-theme-changed',
] as const

export const allowedCommands: ReadonlySet<string> = new Set(allowedCommandNames)
export const allowedEvents: ReadonlySet<string> = new Set(allowedEventNames)
