/* auto-generated by NAPI-RS */

export declare class NativeSearchIndex {
  constructor()
  open(indexPath: string): void
  close(): void
  hasDocuments(): boolean
  rebuild(documents: Array<SearchDocument>): void
  upsertDocument(document: SearchDocument): void
  removeDocument(path: string): void
  removePathPrefix(prefix: string): void
  search(query: string, limit: number): Array<SearchResult>
}

export interface SearchDocument {
  path: string
  title: string
  content: string
}

export interface SearchHighlight {
  start: number
  end: number
}

export interface SearchResult {
  path: string
  title: string
  line: number
  column: number
  endColumn: number
  snippet: string
  snippetHighlights: Array<SearchHighlight>
  score: number
}
