import type { PlateSlashCommandLabels } from '@/components/plate/slash/types'

export const plateSlashTestLabels: PlateSlashCommandLabels = {
  advancedGroup: 'Advanced',
  bold: 'Bold',
  bulletList: 'Bullet list',
  calendarFile: 'Calendar file',
  calendarFilePrompt: 'Calendar file name',
  calloutCaution: 'Caution callout',
  calloutImportant: 'Important callout',
  calloutNote: 'Note callout',
  calloutTip: 'Tip callout',
  calloutWarning: 'Warning callout',
  cancel: 'Cancel',
  clearFormat: 'Clear format',
  codeBash: 'Bash code',
  codeBlock: 'Code block',
  codeHtml: 'HTML code',
  codeJavaScript: 'JavaScript code',
  codeJson: 'JSON code',
  codeTypeScript: 'TypeScript code',
  details: 'Details',
  divider: 'Divider',
  footnote: 'Footnote',
  frontmatter: 'Frontmatter',
  heading1: 'Heading 1',
  heading2: 'Heading 2',
  heading3: 'Heading 3',
  heading4: 'Heading 4',
  heading5: 'Heading 5',
  heading6: 'Heading 6',
  image: 'Image',
  imageAltPrompt: 'Enter image description',
  imageUrl: 'Image URL',
  imageUrlPrompt: 'Enter image URL',
  inlineCode: 'Inline code',
  insertionError: 'Insertion failed',
  italic: 'Italic',
  link: 'Link',
  linkTextPrompt: 'Enter link text',
  linkUrlPrompt: 'Enter link URL',
  listGroup: 'List',
  mermaid: 'Mermaid diagram',
  noResults: 'No commands found',
  orderedList: 'Ordered list',
  quote: 'Quote',
  strike: 'Strikethrough',
  table: 'Table',
  taskList: 'Task list',
  text: 'Text',
  textGroup: 'Text',
  toc: 'Table of contents',
}
