[package]
name = "knowledge-engine"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
fluxdi.workspace = true
marklab-knowledge-rpc-server = { path = "../../crates/rpc-server" }
tracing.workspace = true
tracing-subscriber.workspace = true

[[bin]]
name = "knowledge-engine"
path = "src/main.rs"
